//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shimakaze.Mythic.Editor.I18n {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shimakaze.Mythic.Editor.I18n.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Conditions 的本地化字符串。
        /// </summary>
        public static string LV_Conditions_Header {
            get {
                return ResourceManager.GetString("LV_Conditions.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shimakaze.Mythic.Editor 的本地化字符串。
        /// </summary>
        public static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ActivationRange 的本地化字符串。
        /// </summary>
        public static string NB_ActivationRange_Header {
            get {
                return ResourceManager.GetString("NB_ActivationRange.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ActiveMobs 的本地化字符串。
        /// </summary>
        public static string NB_ActiveMobs_Header {
            get {
                return ResourceManager.GetString("NB_ActiveMobs.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cooldown 的本地化字符串。
        /// </summary>
        public static string NB_Cooldown_Header {
            get {
                return ResourceManager.GetString("NB_Cooldown.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CooldownTimer 的本地化字符串。
        /// </summary>
        public static string NB_CooldownTimer_Header {
            get {
                return ResourceManager.GetString("NB_CooldownTimer.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LeashRange 的本地化字符串。
        /// </summary>
        public static string NB_LeashRange_Header {
            get {
                return ResourceManager.GetString("NB_LeashRange.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MaxMobs 的本地化字符串。
        /// </summary>
        public static string NB_MaxMobs_Header {
            get {
                return ResourceManager.GetString("NB_MaxMobs.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MobLevel 的本地化字符串。
        /// </summary>
        public static string NB_MobLevel_Header {
            get {
                return ResourceManager.GetString("NB_MobLevel.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MobsPerSpawn 的本地化字符串。
        /// </summary>
        public static string NB_MobsPerSpawn_Header {
            get {
                return ResourceManager.GetString("NB_MobsPerSpawn.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Radius 的本地化字符串。
        /// </summary>
        public static string NB_Radius_Header {
            get {
                return ResourceManager.GetString("NB_Radius.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RadiusY 的本地化字符串。
        /// </summary>
        public static string NB_RadiusY_Header {
            get {
                return ResourceManager.GetString("NB_RadiusY.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warmup 的本地化字符串。
        /// </summary>
        public static string NB_Warmup_Header {
            get {
                return ResourceManager.GetString("NB_Warmup.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WarmupTimer 的本地化字符串。
        /// </summary>
        public static string NB_WarmupTimer_Header {
            get {
                return ResourceManager.GetString("NB_WarmupTimer.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 X 的本地化字符串。
        /// </summary>
        public static string NB_X_Header {
            get {
                return ResourceManager.GetString("NB_X.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Y 的本地化字符串。
        /// </summary>
        public static string NB_Y_Header {
            get {
                return ResourceManager.GetString("NB_Y.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Z 的本地化字符串。
        /// </summary>
        public static string NB_Z_Header {
            get {
                return ResourceManager.GetString("NB_Z.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Spawner 的本地化字符串。
        /// </summary>
        public static string NI_Spawner_Content {
            get {
                return ResourceManager.GetString("NI_Spawner.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open 的本地化字符串。
        /// </summary>
        public static string OpenFile_Content {
            get {
                return ResourceManager.GetString("OpenFile.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save As 的本地化字符串。
        /// </summary>
        public static string SaveAsFile_Content {
            get {
                return ResourceManager.GetString("SaveAsFile.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string SaveFile_Content {
            get {
                return ResourceManager.GetString("SaveFile.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MobName 的本地化字符串。
        /// </summary>
        public static string TB_MobName_Header {
            get {
                return ResourceManager.GetString("TB_MobName.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SpawnerGroup 的本地化字符串。
        /// </summary>
        public static string TB_SpawnerGroup_Header {
            get {
                return ResourceManager.GetString("TB_SpawnerGroup.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Spawner Name: 的本地化字符串。
        /// </summary>
        public static string TB_SpawnerName_Header {
            get {
                return ResourceManager.GetString("TB_SpawnerName.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 World 的本地化字符串。
        /// </summary>
        public static string TB_World_Header {
            get {
                return ResourceManager.GetString("TB_World.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Breakable 的本地化字符串。
        /// </summary>
        public static string TS_Breakable_Content {
            get {
                return ResourceManager.GetString("TS_Breakable.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CheckForPlayers 的本地化字符串。
        /// </summary>
        public static string TS_CheckForPlayers_Content {
            get {
                return ResourceManager.GetString("TS_CheckForPlayers.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HealOnLeash 的本地化字符串。
        /// </summary>
        public static string TS_HealOnLeash_Content {
            get {
                return ResourceManager.GetString("TS_HealOnLeash.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ResetThreatOnLeash 的本地化字符串。
        /// </summary>
        public static string TS_ResetThreatOnLeash_Content {
            get {
                return ResourceManager.GetString("TS_ResetThreatOnLeash.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ShowFlames 的本地化字符串。
        /// </summary>
        public static string TS_ShowFlames_Content {
            get {
                return ResourceManager.GetString("TS_ShowFlames.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UseTimer 的本地化字符串。
        /// </summary>
        public static string TS_UseTimer_Content {
            get {
                return ResourceManager.GetString("TS_UseTimer.Content", resourceCulture);
            }
        }
    }
}
